Repository wakawaka-CONTACTO/contacto-server, pull requests merged in 2025-03, with the labels that each got.

#95 [FIX] 로컬 프로파일에서 다중 db 적용
  chat-service/build.gradle
  gateway-service/build.gradle
  user-service/build.gradle
  user-service/src/main/java/org/kiru/user/config/JpaConfig.java
Labels: bug, fix

#108 [FEAT] 좋아요한 인원 추천하지 않음
  user-service/src/main/java/org/kiru/user/portfolio/service/PortfolioService.java
  user-service/src/main/java/org/kiru/user/userlike/adapter/UserLikeJpaAdapter.java
  user-service/src/main/java/org/kiru/user/userlike/adapter/UserLikeMongoAdapter.java
  user-service/src/main/java/org/kiru/user/userlike/repository/UserLikeJpaRepository.java
  user-service/src/main/java/org/kiru/user/userlike/repository/UserLikeMongoRepository.java
  user-service/src/main/java/org/kiru/user/userlike/service/out/GetUserLikeQuery.java
Labels: develop

#116 [FIX] 메시지 객체 반환 형태 수정
  chat-service/src/main/java/org/kiru/chat/event/MessageEventListener.java
Labels: bug, fix

#106 [FIX] 회원 정보 중 포트폴리오 파일 업데이트 시 발생하는 오류 해결
  .gitignore
  core/src/main/java/org/kiru/core/user/userPortfolioItem/domain/UserPortfolio.java
  user-service/src/main/java/org/kiru/user/portfolio/dto/req/AddMultipartFileDto.java
  user-service/src/main/java/org/kiru/user/portfolio/dto/req/PortfolioImagesRequest.java
  user-service/src/main/java/org/kiru/user/user/adapter/UserRepositoryAdapter.java
  user-service/src/main/java/org/kiru/user/user/controller/UserUpdateController.java
  user-service/src/main/java/org/kiru/user/user/dto/request/UserUpdateDto.java
  user-service/src/test/java/org/kiru/user/user/service/out/UserUpdatePortTest.java
Labels: bug

#127 [FIX] ChatList 페이지네이션 반영 - #120
  .gitignore
  chat-service/src/main/java/org/kiru/chat/adapter/in/web/ChatRoomController.java
  chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/ChatRoomRepositoryAdapter.java
  chat-service/src/main/java/org/kiru/chat/application/port/in/GetChatRoomUseCase.java
  chat-service/src/main/java/org/kiru/chat/application/port/out/GetChatRoomQuery.java
  chat-service/src/main/java/org/kiru/chat/application/service/ChatService.java
  core/src/main/java/org/kiru/core/common/PageableResponse.java
  user-service/src/main/java/org/kiru/user/admin/controller/AdminController.java
  user-service/src/main/java/org/kiru/user/user/api/ChatApiClient.java
  user-service/src/main/java/org/kiru/user/user/controller/UserController.java
  user-service/src/main/java/org/kiru/user/user/service/UserService.java
Labels: fix

#162 [FEAT] 알림 서비스 CI/CD 구축
  .github/workflows/alarm-cd.yml
  .github/workflows/alarm-ci.yml
Labels: feature

#159 [FIX] 사용자 추천 알고리즘 로직 수정 - #156
  core/src/main/java/org/kiru/core/user/common/BaseTimeEntity.java
  core/src/main/java/org/kiru/core/user/userlike/domain/UserLike.java
  core/src/main/java/org/kiru/core/user/userlike/entity/UserLikeJpaEntity.java
  core/src/main/java/org/kiru/core/user/userlike/entity/UserLikeMongoEntity.java
  user-service/src/main/java/org/kiru/user/portfolio/adapter/UserRecommendAdapter.java
  user-service/src/main/java/org/kiru/user/portfolio/controller/PortfolioController.java
  user-service/src/main/java/org/kiru/user/portfolio/service/PortfolioService.java
  user-service/src/main/java/org/kiru/user/portfolio/service/out/GetRecommendUserIdsQuery.java
  user-service/src/main/java/org/kiru/user/user/repository/UserRepository.java
  user-service/src/main/java/org/kiru/user/userBlock/adapter/UserBlockJpaAdapter.java
  user-service/src/main/java/org/kiru/user/userBlock/repository/UserBlockJpaRepository.java
  user-service/src/main/java/org/kiru/user/userBlock/service/out/GetUserBlockQuery.java
  user-service/src/main/java/org/kiru/user/userlike/adapter/UserLikeJpaAdapter.java
  user-service/src/main/java/org/kiru/user/userlike/adapter/UserLikeMongoAdapter.java
  user-service/src/main/java/org/kiru/user/userlike/repository/UserLikeJpaRepository.java
  user-service/src/main/java/org/kiru/user/userlike/service/out/GetUserLikeQuery.java
  user-service/src/test/java/org/kiru/user/userlike/service/out/SendLikeOrDislikeUseCaseTest.java
Labels: fix
